# Generated by Django 2.2.12 on 2021-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('myfile', models.FileField(default='', upload_to='images')),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
